# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefselect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='bannedbook',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
